<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class ProcurementStatusUpdateABC extends Migration
{
    public function up()
    {
        $this->forge->addColumn('procurement_status', [
            'CONSTRAINT fk_procurement FOREIGN KEY (procurement_id) REFERENCES procurement(procurement_id) ON DELETE CASCADE ON UPDATE CASCADE'
        ]);
    }

    public function down()
    {
        // You will need to find the specific constraint name generated by your DBMS after adding it, as it may not be 'fk_procurement'
        $this->forge->dropForeignKey('procurement_status', 'fk_procurement');
    }
}
